language: java
sudo: required
before_install:
- sudo rm /usr/local/bin/docker-compose
- curl -L https://github.com/docker/compose/releases/download/1.20.1/docker-compose-`uname -s`-`uname -m` > docker-compose
- chmod +x docker-compose
- chmod +x mvnw
- sudo mv docker-compose /usr/local/bin
- docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
install:
- mvn install -Dmaven.javadoc.skip=true -B -V
- ls -l
- docker build --build-arg JAR_FILE=/target/project.jar -t mariomans/234project-backend .
- docker push mariomans/234project-backend
- docker pull dto80/project234-frontend
cache:
 directories:
 - "$HOME/.m2"