version: '3.3'
services:
  frontend:
    image: dto80/project234-frontend:latest
    ports:
      - "8087:80"
    volumes :
      - type: bind
        source: ./settings
        target: /usr/share/nginx/html/assets
  backend:
    image: mariomans/234project-backend:latest
    ports:
      - "8086:8080"